// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TestProjectDemo.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NavigationDuSiteFeature : object, global::Xunit.IClassFixture<NavigationDuSiteFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("fr"), "Features", "Navigation du site", "  En tant qu utilisateur authentifie\r\n  Je veux naviguer entre toutes les pages d" +
                "e l application\r\n  Afin d atteindre Accueil, A propos, Contact et Connexion/Deco" +
                "nnexion", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Navigation.feature"
#line hidden
        
        public NavigationDuSiteFeature(NavigationDuSiteFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("je suis authentifie en tant que \"admin\" avec le mot de passe \"admin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné que ");
#line hidden
#line 9
    await testRunner.AndAsync("je ouvre la page accueil", ((string)(null)), ((global::Reqnroll.Table)(null)), "Et que ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Navigation.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Navigation vers une page depuis la barre de navigation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Navigation du site")]
        [global::Xunit.TraitAttribute("Description", "Navigation vers une page depuis la barre de navigation")]
        [global::Xunit.InlineDataAttribute("Home", "accueil", "Home Page", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("About", "apropos", "About", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("Contact", "contact", "Contact", "2", new string[0])]
        public async global::System.Threading.Tasks.Task NavigationVersUnePageDepuisLaBarreDeNavigation(string lien, string page, string titre, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Lien", lien);
            argumentsOfScenario.Add("Page", page);
            argumentsOfScenario.Add("Titre", titre);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navigation vers une page depuis la barre de navigation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync(string.Format("je clique sur le lien \"{0}\"", lien), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 13
    await testRunner.ThenAsync(string.Format("je suis sur la page {0}", page), ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("le titre de la page contient \"{0}\"", titre), ((string)(null)), ((global::Reqnroll.Table)(null)), "Et ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Le lien de la marque ramene a l accueil")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Navigation du site")]
        [global::Xunit.TraitAttribute("Description", "Le lien de la marque ramene a l accueil")]
        public async global::System.Threading.Tasks.Task LeLienDeLaMarqueRameneALAccueil()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Le lien de la marque ramene a l accueil", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 23
    await testRunner.GivenAsync("je ouvre la page apropos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Étant donné que ");
#line hidden
#line 24
    await testRunner.WhenAsync("je clique sur le lien \"Application name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 25
    await testRunner.ThenAsync("je suis sur la page accueil", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Parcours de navigation complet sur toutes les pages")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Navigation du site")]
        [global::Xunit.TraitAttribute("Description", "Parcours de navigation complet sur toutes les pages")]
        public async global::System.Threading.Tasks.Task ParcoursDeNavigationCompletSurToutesLesPages()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Parcours de navigation complet sur toutes les pages", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.WhenAsync("je clique sur le lien \"About\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 29
    await testRunner.ThenAsync("je suis sur la page apropos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 30
    await testRunner.WhenAsync("je clique sur le lien \"Contact\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 31
    await testRunner.ThenAsync("je suis sur la page contact", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 32
    await testRunner.WhenAsync("je clique sur le lien \"Home\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 33
    await testRunner.ThenAsync("je suis sur la page accueil", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
#line 34
    await testRunner.WhenAsync("je clique sur le lien \"Logout\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quand ");
#line hidden
#line 35
    await testRunner.ThenAsync("la page de connexion est affichee", ((string)(null)), ((global::Reqnroll.Table)(null)), "Alors ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await NavigationDuSiteFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await NavigationDuSiteFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
